services:
  node-backend:
    build:
      context: ./backend/node-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/node-service:/app
      - /app/node_modules
    profiles:
      - node
    environment:
      - NODE_ENV=development
