services:
  csr-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: csr-frontend
    ports:
      - "5205:5205"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
