services:
  pos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-frontend
    ports:
      - "5207:5207"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
