services:
  customer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-frontend
    ports:
      - "5206:5206"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
