services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=54322
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
