services:
  delivery-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: delivery-frontend
    ports:
      - "5203:5203"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
